name: Run tox

on:
    pull_request:
    push:
      branches:
        - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - python-version: '3.9'
          tox-env: py39
        - python-version: '3.10'
          tox-env: py310
        - python-version: '3.11'
          tox-env: py311
          codecov: codecov
        - python-version: '3.12'
          tox-env: py312
        - python-version: '3.11'
          tox-env: lint
        - python-version: '3.11'
          tox-env: docs
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade tox tox-uv

    - name: Run tox
      run: |
        tox run -e ${{ matrix.tox-env }}

    - name: Upload to codecov
      if: ${{ matrix.codecov == 'codecov' }}
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        files: ./coverage.xml
        flags: pytest
        verbose: true
        name: "${{ github.repository }}-${{ matrix.tox-env }}"
